name: Unit, Functional And Integration Tests

on:
    push:
        branches:
            - "master"
            - "develop"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    prepare:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - name: Checkout Protokol NFT-CORE
              uses: actions/checkout@v2
              with:
                  repository: protokol/core-nft
                  token: ${{ secrets.PAT_TOKEN }}
                  ref: conf/nft-token-develop

            - name: Checkout protokol/nft-dapps
              uses: actions/checkout@v2
              with:
                  path: protokol/

            - name: Cache node modules
              id: yarn-cache
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-

            - name: Use Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install and Build Packages
              run: yarn install && yarn bootstrap

    test-base-api-unit:
        needs: prepare

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - name: Checkout Protokol NFT-CORE
              uses: actions/checkout@v2
              with:
                  repository: protokol/core-nft
                  token: ${{ secrets.PAT_TOKEN }}
                  ref: conf/nft-token-develop

            - name: Checkout protokol/nft-dapps
              uses: actions/checkout@v2
              with:
                  path: protokol/

            - name: Cache node modules
              uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: ${{ runner.os }}-yarn-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install & Build
              run: yarn setup

            - name: Test
              run: |
                 cd protokol/packages/nft-base-api
                 yarn test:unit:coverage --coverageDirectory .coverage/unit-base-api --maxWorkers=2
